apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    name: redis-app
    type: data-base
  ports:
  - port: 6379
    targetPort: 6379

---


apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    name: postgres-app
    type: data-base
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    name: python-app
    type: front-end
  ports:
  - port: 80
    targetPort: 80
    NodePort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    name: nodejs-app
    type: front-end
  ports:
  - port: 80
    targetPort: 80
    NodePort: 80

  

    